# This is a basic workflow to help you get started with Actions

name: Create PDF

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Deploy Jekyll with GitHub Pages dependencies preinstalled"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Create PDF
        id: create-pdf
        uses: grzegorzorwat/GitHubActions.WebpageToPdf@main
        with:
          address: ${{ 'https://grzegorzorwat.github.io/cv/' }}
          output: ${{ './' }}
          file-name: ${{ 'cv.pdf' }}
          append-metadata: false
          commit: ${{ steps.vars.outputs.sha_short }}
          script-path: ${{ './.github/workflows/script.js' }}
          css-path: ${{ './.github/workflows/styles.css' }}
          media-type: 'Print'
          paper-format: 'A4'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: '${{ steps.create-pdf.outputs.title }}'
          commit-message: 'Create PDF.'
          delete-branch: true
  generate2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout cv repo
        uses: actions/checkout@v3
        with: 
          path: cv

      - name: Checkout private cv repo
        uses: actions/checkout@v3
        with: 
          path: private-cv
          repository: grzegorzorwat/private-cv
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Create PDF
        id: create-pdf
        uses: grzegorzorwat/GitHubActions.WebpageToPdf@main
        with:
          address: ${{ 'https://grzegorzorwat.github.io/cv/' }}
          output: ${{ './private-cv' }}
          file-name: ${{ 'cv.pdf' }}
          append-metadata: false
          commit: ${{ steps.vars.outputs.sha_short }}
          script-path: ${{ './cv/.github/workflows/script.js' }}
          css-path: ${{ './cv/.github/workflows/styles.css' }}
          media-type: 'Print'
          paper-format: 'A4'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          path: private-cv
          title: '${{ steps.create-pdf.outputs.title }}'
          commit-message: 'Create PDF.'
          delete-branch: true
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
