# This is a basic workflow to help you get started with Actions

name: Create PDF

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Create PDF
        id: create-pdf
        uses: grzegorzorwat/GitHubActions.WebpageToPdf@main
        with:
          address: ${{ 'https://grzegorzorwat.github.io/cv/' }}
          output: ${{ './pdfs' }}
          file-name: ${{ 'cv.pdf' }}
          append-metadata: true
          commit: ${{ steps.vars.outputs.sha_short }}
          script-path: ${{ './.github/workflows/script.js' }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: '${{ steps.create-pdf.outputs.title }}'
          commit-message: 'Create PDF.'
          delete-branch: true
